### PR TITLE
Lint.jl 0.3.0 has been released

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by TeroFrondelius** [comment]
The METADATA tag has not been merged yet. See here: https://github.com/JuliaLang/METADATA.jl/pull/8268, ping me when this happens and I will merge this pull request.

**Comment by waldyrious** [comment]
Oh, my bad, thanks for the heads-up. I've subscribed to that thread and will ping you once it's resolved.

**Comment by TotalVerb** [comment]
Since versions that change the minimum Julia version must be minor or major releases, we need to retag that. See https://github.com/JuliaLang/METADATA.jl/pull/8321 for the 0.3.0 tag, which is correct.

Going forward, following SemVer, almost every feature should get a minor version bump at least.

**Comment by waldyrious** [comment]
I've updated this PR to change the mention of Lint.jl's version as well.

**Pull request merged**
